### ISSUE TITLE
Missing folder for Maldet deploy?

### ISSUE THREAD

**Issue by tristanvs** [lyrasis/ansible-linux-security-role#3]
fatal: [clients.votresite.ca]: FAILED! => {"changed": false, "failed": true, "msg": "dest '/root/downloads/maldet' must be an existing dir"}
fatal: [node1.votresite.ca]: FAILED! => {"changed": false, "failed": true, "msg": "dest '/root/downloads/maldet' must be an existing dir"}

all of the rest is going pretty swimmingly. should I alter it to include creating this folder? 

cheers!

**Comment by Blake-** [comment]
@tristanvs Thanks for the heads up! You're right, that should have a dir created.

**Comment by tristanvs** [comment]
No problem! However, i'm a noob with this. I did go ahead and create the folder. Now we have another issue. The maldet executable does download, and decompress. But the maldet folder ends up in another versionned subfolder.

ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

added:
- name: Create maldet folder
    file: path=/root/downloads/maldet state=directory

modified (to reflect new changes in Ansible 2.3):
  - name: Maldet | Download AND unarchive copied package
    become: root
    unarchive: src=http://www.rfxn.com/downloads/maldetect-current.tar.gz creates=/root/downloads/maldet dest=/root/downloads/maldet remote_src=yes
    tags: maldet
    tags: scanners

(PS: i believe that tags are not right with the new version, Ansible complains about duplicates).

So, with this, for some reason, Ansible considers that the folder already exists, and skips the task:
 TASK [ansible-linux-security-role : Maldet | Unarchive copied package] *************************************************************************************************************************************************************
skipping: [node1.votresite.ca]
skipping: [clients.votresite.ca]

I managed once to do a download and decompress (i can't remember how). But then the next step failed, because maldet decompresses in a subfolder that is versioned (ex: maldetect-1.6.2) instead of the /root/downloads/maldet, so the installation step fails.

Any clue on how I could fix that? Sorry again, i'm still very new to this.

Cheers

**Comment by Blake-** [comment]
I just pushed a bunch of little changes, let me know if that fixes it for you.

**Comment by tristanvs** [comment]
You're awesome, thank you! Gonna do a pull and test all that. Thanks again!

Cheers

**Comment by tristanvs** [comment]
You, sir, are a gentleman and a scholar!

The maldet part works flawlessly now, but I got an issue at the Lynis download step. I'll post it here, but I can totally post it as a new issue if you want me to.

TASK [ansible-linux-security-role : Lynis | Grab the latest Lynis] *****************************************************************************************************************************************************************
fatal: [clients.votresite.ca]: FAILED! => {"changed": false, "dest": "/root/downloads", "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "https://cisofy.com/files/lynis-2.1.1.tar.gz"}
fatal: [node1.votresite.ca]: FAILED! => {"changed": false, "dest": "/root/downloads", "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "https://cisofy.com/files/lynis-2.1.1.tar.gz"}

**Comment by Blake-** [comment]
Ah, that version is way old now use:
lynis_version: lynis-2.5.3.tar.gz

**Comment by tristanvs** [comment]
Like Homer would say, DOH! Forgot to put my vars file back, simply ;)

However, I still have a failed Lynis install:

TASK [ansible-linux-security-role : Lynis | Install Lynis] *************************************************************************************************************************************************************************
fatal: [clients.votresite.ca]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to clients.votresite.ca closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_DNox_L/ansible_module_command.py\", line 220, in <module>\r\n    main()\r\n  File \"/tmp/ansible_DNox_L/ansible_module_command.py\", line 197, in main\r\n    rc, out, err = module.run_command(args, executable=executable, use_unsafe_shell=shell, encoding=None)\r\n  File \"/tmp/ansible_DNox_L/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2486, in run_command\r\nOSError: [Errno 2] No such file or directory: '/root/downloads/lynis'\r\n", "msg": "MODULE FAILURE", "rc": 0}
fatal: [node1.votresite.ca]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to node1.votresite.ca closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n

**Comment by Blake-** [comment]
Just pushed a fix, hopefully

**Comment by tristanvs** [comment]
- name: Lynis | Install Lynis
    command: mv /root/downloads/lynis /etc/lynis chdir=/root/downloads/lynis creates=/etc/lynis
    tags:
      - lynis
      - scanners

Is it possible the chdir which changes to that directory before doing the move, sort of conflicts?

**Comment by tristanvs** [comment]
Fetching it and testing

**Comment by tristanvs** [comment]
smells like success!!

Thank you so much, my good sir! Thanks to you, i'm also learning a lot!

Cheers

Tristan
